name: CI
on:
  workflow_dispatch:
  pull_request:
  # Triggering CI on default branch improves caching
  # see https://docs.github.com/en/free-pro-team@latest/actions/guides/caching-dependencies-to-speed-up-workflows#restrictions-for-accessing-a-cache
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    # Required by aws-actions/configure-aws-credentials
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: corretto
          java-version: 11
          cache: sbt
      - name: CDK
        run: |
          (
            cd cdk
            npm ci
            npm test
            npm run synth
          )
      - name: Assume AWS role required for Riff-Raff upload
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.GU_RIFF_RAFF_ROLE_ARN }}
          aws-region: eu-west-1
      - name: Build, test and upload artifact
        run: sbt -v "test ;assembly ;riffRaffUpload"
      - name: Test Summary
        uses: test-summary/action@v2
        if: always()
        with:
          paths: "test-results/**/TEST-*.xml"
